services:
  mysql:
    image: mysql:${MYSQL_VERSION}
    restart: always
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - "./.tmp/database:/var/lib/mysql"

  php-fpm:
    build:
      dockerfile: docker/php-fpm/Dockerfile
      args:
        PHP_VERSION: ${PHP_VERSION}
    restart: always
    volumes:
      - "./docker/php-fpm/custom.php.ini:/usr/local/etc/php/conf.d/custom.ini"
      - "./laravel:/var/www/html"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    depends_on:
      - mysql
    ports:
      - "${PMA_PORT}:80"
    environment:
      PMA_HOST: mysql # link to service name
      MYSQL_USERNAME: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}

  nginx:
    image: nginx:stable-alpine
    restart: always
    depends_on:
      - php-fpm
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - "./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro"
      - "./laravel:/var/www/html"

  composer:
    image: composer:${COMPOSER_VERSION}
    container_name: composer
    working_dir: /app
    volumes:
      - ./laravel:/app

  node:
    image: node:${NODE_VERSION}
    container_name: node
    working_dir: /app
    volumes:
      - ./laravel:/app

  artisan:
    build:
      dockerfile: docker/php-fpm/Dockerfile
      args:
        PHP_VERSION: ${PHP_VERSION}
    volumes:
      - "./laravel:/var/www/html"
    entrypoint: ["php", "/var/www/html/artisan"]

